// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logDnorm
double logDnorm(double x, double mu, double s2);
RcppExport SEXP _latent_logDnorm(SEXP xSEXP, SEXP muSEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(logDnorm(x, mu, s2));
    return rcpp_result_gen;
END_RCPP
}
// optimizer
Rcpp::List optimizer(Rcpp::List control_manifold, Rcpp::List control_transform, Rcpp::List control_estimator, Rcpp::List control_optimizer);
RcppExport SEXP _latent_optimizer(SEXP control_manifoldSEXP, SEXP control_transformSEXP, SEXP control_estimatorSEXP, SEXP control_optimizerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type control_manifold(control_manifoldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_transform(control_transformSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_estimator(control_estimatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_optimizer(control_optimizerSEXP);
    rcpp_result_gen = Rcpp::wrap(optimizer(control_manifold, control_transform, control_estimator, control_optimizer));
    return rcpp_result_gen;
END_RCPP
}
// polyfast
Rcpp::List polyfast(arma::mat data, std::string missing, const std::string acov, const std::string smooth, double min_eigval, const int nboot, const bool fit, const int cores);
RcppExport SEXP _latent_polyfast(SEXP dataSEXP, SEXP missingSEXP, SEXP acovSEXP, SEXP smoothSEXP, SEXP min_eigvalSEXP, SEXP nbootSEXP, SEXP fitSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type missing(missingSEXP);
    Rcpp::traits::input_parameter< const std::string >::type acov(acovSEXP);
    Rcpp::traits::input_parameter< const std::string >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< double >::type min_eigval(min_eigvalSEXP);
    Rcpp::traits::input_parameter< const int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< const bool >::type fit(fitSEXP);
    Rcpp::traits::input_parameter< const int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(polyfast(data, missing, acov, smooth, min_eigval, nboot, fit, cores));
    return rcpp_result_gen;
END_RCPP
}
// grad_comp
Rcpp::List grad_comp(arma::vec parameters, Rcpp::List control_manifold, Rcpp::List control_transform, Rcpp::List control_estimator, Rcpp::List control_optimizer, double eps);
RcppExport SEXP _latent_grad_comp(SEXP parametersSEXP, SEXP control_manifoldSEXP, SEXP control_transformSEXP, SEXP control_estimatorSEXP, SEXP control_optimizerSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_manifold(control_manifoldSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_transform(control_transformSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_estimator(control_estimatorSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_optimizer(control_optimizerSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_comp(parameters, control_manifold, control_transform, control_estimator, control_optimizer, eps));
    return rcpp_result_gen;
END_RCPP
}
// count
std::vector<int> count(const std::vector<int>& X, const int n, const int max_X);
RcppExport SEXP _latent_count(SEXP XSEXP, SEXP nSEXP, SEXP max_XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type max_X(max_XSEXP);
    rcpp_result_gen = Rcpp::wrap(count(X, n, max_X));
    return rcpp_result_gen;
END_RCPP
}
// joint_frequency_table
std::vector<std::vector<int>> joint_frequency_table(const std::vector<int>& X, const int n, const int max_X, const std::vector<int>& Y, const int max_Y);
RcppExport SEXP _latent_joint_frequency_table(SEXP XSEXP, SEXP nSEXP, SEXP max_XSEXP, SEXP YSEXP, SEXP max_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type max_X(max_XSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int >::type max_Y(max_YSEXP);
    rcpp_result_gen = Rcpp::wrap(joint_frequency_table(X, n, max_X, Y, max_Y));
    return rcpp_result_gen;
END_RCPP
}
// dbinorm
double dbinorm(double p, double x, double y);
RcppExport SEXP _latent_dbinorm(SEXP pSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dbinorm(p, x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_latent_logDnorm", (DL_FUNC) &_latent_logDnorm, 3},
    {"_latent_optimizer", (DL_FUNC) &_latent_optimizer, 4},
    {"_latent_polyfast", (DL_FUNC) &_latent_polyfast, 8},
    {"_latent_grad_comp", (DL_FUNC) &_latent_grad_comp, 6},
    {"_latent_count", (DL_FUNC) &_latent_count, 3},
    {"_latent_joint_frequency_table", (DL_FUNC) &_latent_joint_frequency_table, 5},
    {"_latent_dbinorm", (DL_FUNC) &_latent_dbinorm, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_latent(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
