# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft <- function(x, a) {
    .Call(`_latent_soft`, x, a)
}

duplication <- function(p, halflower = TRUE) {
    .Call(`_latent_duplication`, p, halflower)
}

mytest <- function(p) {
    .Call(`_latent_mytest`, p)
}

optimizer <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_optimizer`, control_manifold, control_transform, control_estimator, control_optimizer)
}

polyfast <- function(data, missing = "pairwise.complete.cases", acov = "none", smooth = "none", min_eigval = 0.001, nboot = 1000L, fit = FALSE, cores = 1L) {
    .Call(`_latent_polyfast`, data, missing, acov, smooth, min_eigval, nboot, fit, cores)
}

asymptotic_normal <- function(P) {
    .Call(`_latent_asymptotic_normal`, P)
}

asymptotic_elliptical <- function(P, eta = 1.00) {
    .Call(`_latent_asymptotic_elliptical`, P, eta)
}

asymptotic_general <- function(X) {
    .Call(`_latent_asymptotic_general`, X)
}

DACOV2 <- function(n, poly, tabs, taus, mvphis) {
    .Call(`_latent_DACOV2`, n, poly, tabs, taus, mvphis)
}

orth <- function(X) {
    .Call(`_latent_orth`, X)
}

oblq <- function(X) {
    .Call(`_latent_oblq`, X)
}

poblq <- function(X, target) {
    .Call(`_latent_poblq`, X, target)
}

rorth <- function(p, q) {
    .Call(`_latent_rorth`, p, q)
}

roblq <- function(p, q) {
    .Call(`_latent_roblq`, p, q)
}

lyap_sym <- function(Y, Q) {
    .Call(`_latent_lyap_sym`, Y, Q)
}

rpoblq <- function(p, q, target) {
    .Call(`_latent_rpoblq`, p, q, target)
}

grad_comp <- function(control_manifold, control_transform, control_estimator, control_optimizer, compute = "all", eps = 1e-04) {
    .Call(`_latent_grad_comp`, control_manifold, control_transform, control_estimator, control_optimizer, compute, eps)
}

get_grad <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_get_grad`, control_manifold, control_transform, control_estimator, control_optimizer)
}

get_hess <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_get_hess`, control_manifold, control_transform, control_estimator, control_optimizer)
}

get_vcov <- function(control_manifold, control_transform, control_estimator, control_optimizer, H) {
    .Call(`_latent_get_vcov`, control_manifold, control_transform, control_estimator, control_optimizer, H)
}

get_jacob <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_get_jacob`, control_manifold, control_transform, control_estimator, control_optimizer)
}

gLPS_uls <- function(S, Lambda, Phi) {
    .Call(`_latent_gLPS_uls`, S, Lambda, Phi)
}

gLPS_ml <- function(S, Lambda, Phi) {
    .Call(`_latent_gLPS_ml`, S, Lambda, Phi)
}

real_sqrtmat <- function(R) {
    .Call(`_latent_real_sqrtmat`, R)
}

count <- function(X, n, max_X) {
    .Call(`_latent_count`, X, n, max_X)
}

joint_frequency_table <- function(X, n, max_X, Y, max_Y) {
    .Call(`_latent_joint_frequency_table`, X, n, max_X, Y, max_Y)
}

MVPHI <- function(z) {
    .Call(`_latent_MVPHI`, z)
}

dbinorm <- function(p, x, y) {
    .Call(`_latent_dbinorm`, p, x, y)
}

pbinorm <- function(lower0, lower1, upper0, upper1, rho, mvphi0, mvphi1, mvphi2, mvphi3) {
    .Call(`_latent_pbinorm`, lower0, lower1, upper0, upper1, rho, mvphi0, mvphi1, mvphi2, mvphi3)
}

fpoly <- function(p, tau1, tau2, mvphi1, mvphi2, n) {
    .Call(`_latent_fpoly`, p, tau1, tau2, mvphi1, mvphi2, n)
}

fpoly2 <- function(R, tau, mvphi, n) {
    .Call(`_latent_fpoly2`, R, tau, mvphi, n)
}

poly_deriv <- function(rho, tau1, tau2, mvphi1, mvphi2, n) {
    .Call(`_latent_poly_deriv`, rho, tau1, tau2, mvphi1, mvphi2, n)
}

