# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logDnorm <- function(x, mu, s2) {
    .Call(`_latent_logDnorm`, x, mu, s2)
}

optimizer <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_optimizer`, control_manifold, control_transform, control_estimator, control_optimizer)
}

polyfast <- function(data, missing = "pairwise.complete.cases", acov = "none", smooth = "none", min_eigval = 0.001, nboot = 1000L, fit = FALSE, cores = 1L) {
    .Call(`_latent_polyfast`, data, missing, acov, smooth, min_eigval, nboot, fit, cores)
}

grad_comp <- function(parameters, control_manifold, control_transform, control_estimator, control_optimizer, compute = "all", eps = 1e-04) {
    .Call(`_latent_grad_comp`, parameters, control_manifold, control_transform, control_estimator, control_optimizer, compute, eps)
}

count <- function(X, n, max_X) {
    .Call(`_latent_count`, X, n, max_X)
}

joint_frequency_table <- function(X, n, max_X, Y, max_Y) {
    .Call(`_latent_joint_frequency_table`, X, n, max_X, Y, max_Y)
}

dbinorm <- function(p, x, y) {
    .Call(`_latent_dbinorm`, p, x, y)
}

