# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dxt <- function(p, q) {
    .Call(`_latent_dxt`, p, q)
}

commutation <- function(m, n) {
    .Call(`_latent_commutation`, m, n)
}

soft <- function(x, a) {
    .Call(`_latent_soft`, x, a)
}

duplication <- function(p, halflower = TRUE, halfmatrix = TRUE) {
    .Call(`_latent_duplication`, p, halflower, halfmatrix)
}

mytest <- function(p) {
    .Call(`_latent_mytest`, p)
}

optimizer <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_optimizer`, control_manifold, control_transform, control_estimator, control_optimizer)
}

polyfast <- function(data, missing = "pairwise.complete.cases", smooth = "none", min_eigval = 0.001, nboot = 1000L, fit = FALSE, cores = 1L) {
    .Call(`_latent_polyfast`, data, missing, smooth, min_eigval, nboot, fit, cores)
}

asymptotic_normal <- function(S, cov = TRUE, diag = TRUE) {
    .Call(`_latent_asymptotic_normal`, S, cov, diag)
}

asymptotic_elliptical <- function(S, eta = 1.00, cov = TRUE, diag = TRUE) {
    .Call(`_latent_asymptotic_elliptical`, S, eta, cov, diag)
}

asymptotic_general <- function(X, cov = TRUE, diag = TRUE) {
    .Call(`_latent_asymptotic_general`, X, cov, diag)
}

orth <- function(X) {
    .Call(`_latent_orth`, X)
}

oblq <- function(X) {
    .Call(`_latent_oblq`, X)
}

poblq <- function(X, target) {
    .Call(`_latent_poblq`, X, target)
}

rorth <- function(p, q) {
    .Call(`_latent_rorth`, p, q)
}

roblq <- function(p, q) {
    .Call(`_latent_roblq`, p, q)
}

lyap_sym <- function(Y, Q) {
    .Call(`_latent_lyap_sym`, Y, Q)
}

rpoblq <- function(p, q, constraints) {
    .Call(`_latent_rpoblq`, p, q, constraints)
}

grad_comp <- function(control_manifold, control_transform, control_estimator, control_optimizer, compute = "all", eps = 1e-04) {
    .Call(`_latent_grad_comp`, control_manifold, control_transform, control_estimator, control_optimizer, compute, eps)
}

get_grad <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_get_grad`, control_manifold, control_transform, control_estimator, control_optimizer)
}

get_dgrad <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_get_dgrad`, control_manifold, control_transform, control_estimator, control_optimizer)
}

get_hess <- function(control_manifold, control_transform, control_estimator, control_optimizer, cores = 1L) {
    .Call(`_latent_get_hess`, control_manifold, control_transform, control_estimator, control_optimizer, cores)
}

get_vcov <- function(control_manifold, control_transform, control_estimator, control_optimizer, H) {
    .Call(`_latent_get_vcov`, control_manifold, control_transform, control_estimator, control_optimizer, H)
}

get_jacob <- function(control_manifold, control_transform, control_estimator, control_optimizer) {
    .Call(`_latent_get_jacob`, control_manifold, control_transform, control_estimator, control_optimizer)
}

yule_cor_full_rcpp <- function(X_df, ipfp_maxit = 2000L, ipfp_tol = 1e-12, pinv_tol = 1e-12) {
    .Call(`_latent_yule_cor_full_rcpp`, X_df, ipfp_maxit, ipfp_tol, pinv_tol)
}

real_sqrtmat <- function(R) {
    .Call(`_latent_real_sqrtmat`, R)
}

count <- function(X, n, max_X) {
    .Call(`_latent_count`, X, n, max_X)
}

joint_frequency_table <- function(X, n, max_X, Y, max_Y) {
    .Call(`_latent_joint_frequency_table`, X, n, max_X, Y, max_Y)
}

poly_deriv <- function(rho, tau1, tau2, pnorm_tau1, pnorm_tau2, n) {
    .Call(`_latent_poly_deriv`, rho, tau1, tau2, pnorm_tau1, pnorm_tau2, n)
}

fpoly <- function(p, tau1, tau2, pnorm_tau1, pnorm_tau2, n) {
    .Call(`_latent_fpoly`, p, tau1, tau2, pnorm_tau1, pnorm_tau2, n)
}

fpoly2 <- function(R, tau, pnorm_tau, n) {
    .Call(`_latent_fpoly2`, R, tau, pnorm_tau, n)
}

